For linters checking
lucianosarno/responsiveDesign pull request #2
Opened 2020-07-07 19:45 UTC by lucianosarno

First for linters checking, further for code review.

2020-07-08 01:01 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @lucianosarno @karthy1998** 
Nice job with your first submission for this project :muscle:  
You have made good progress  :clap: :clap: :clap:
Still, your project needs some improvements:
- [ ] the screenshot of your project (in the README file) is not loading
- [ ] Your live demo link is broken, to create a live demo you can use the next link: https://raw.githack.com/
- [ ] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition, or you can create a new class.
- [ ] remove commented code in your CSS class

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-07-08 01:01 UTC, andresporras3423 commented on css/style.css
> +} */
Remove commented code

2020-07-08 01:01 UTC, andresporras3423 commented on css/style.css
> +} */
Remove commented code

2020-07-08 01:01 UTC, andresporras3423 commented on css/style.css
> +}
Group selectors with the same style definition, or create a new class.

2020-07-08 01:01 UTC, andresporras3423 commented on css/style.css
> +}
Group this selector with the selector of line 386, or create a new class.

2020-07-08 01:01 UTC, andresporras3423 commented on css/style.css
> +  }
Group selectors with the same style definition, or create a new class.

2020-07-08 10:14 UTC, karthykarthick commented
we use BEM approach

2020-07-08 12:03 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: :stop_sign: 
### HELLO @lucianosarno AM PETER ROBERT A TSE AND I HAVE REVIEWED YOUR PROJECT. :computer: 

### GREAT WORK SO FAR :clap: 

**YOU HAVE DONE SUCH A GREAT JOB BUT STILL THERE ARE AFEW CHANGES TO BE MADE** :arrow_down: 

Kindly fix the following: 

- [x] Your project doesn't have a logo. This should be added at the desktop version of your site :smile: 
### YOURS
![logo](https://user-images.githubusercontent.com/32361963/86915634-f582d200-c12a-11ea-8f85-77c3dd636217.jpg)
### ORIGINAL
![logo original](https://user-images.githubusercontent.com/32361963/86915671-05021b00-c12b-11ea-9e9b-0f4a59b369a3.jpg)

- [x] You don't have a latest deal section in your site. Kindly add it

- [ ] Your footer doesn't look like the original kindly you need to fix that
### YOURS
![footer section](https://user-images.githubusercontent.com/32361963/86915841-53171e80-c12b-11ea-831e-55e25701233e.jpg)
### ORIGINAL
![footer section original](https://user-images.githubusercontent.com/32361963/86915863-5e6a4a00-c12b-11ea-88fa-4f76af4f4732.jpg)

- [ ] Your news section doesn't look like the original kindly make it look like the original site
### YOURS
![news section](https://user-images.githubusercontent.com/32361963/86915956-848fea00-c12b-11ea-824f-5f1cc2185f99.jpg)
### ORIGINAL
![news section original](https://user-images.githubusercontent.com/32361963/86915991-8f4a7f00-c12b-11ea-9b48-66422f6789be.jpg)

- [ ] There is a responsiveness issue with your images at the mobile view. Kindly you need to make sure that your images are not been hidden rather they respond according to the screen size. This should be the behaviour of a good responsive site
![responsiveness issue](https://user-images.githubusercontent.com/32361963/86916152-d2a4ed80-c12b-11ea-9de8-0d5ddb41ce29.jpg)

- [ ] There are some validation errors in your HTML and CSS document kindly fix that
![css errors](https://user-images.githubusercontent.com/32361963/86916209-ef412580-c12b-11ea-878b-6dbd38e815db.jpg)
![validation error](https://user-images.githubusercontent.com/32361963/86916258-04b64f80-c12c-11ea-8e84-315e06ac0419.jpg)

**once you have fixed all the above submit your project for another review** :smile: 

### HAPPY CODING :computer:

2020-07-08 17:30 UTC, BrittanyBlake requested changes
## Status: Changes Required ♻️ 
****
### Hi @karthykarthick and @lucianosarno! 👋 👋 
You guys have done a great job working on the TSE feedback so far!👍Your project looks really good! 👏 👏   There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

### Navigation Bar

- **Medium version**

- [x] The TNW logo should appear on the medium screen size. Please compare your clone with the original page and add this. 
Your clone 👇 
![Screen Shot 2020-07-08 at 7 00 57 PM](https://user-images.githubusercontent.com/48804258/86948392-5c18e780-c14d-11ea-8c9a-4e521aa11d74.png)
The original page 👇 
![Screen Shot 2020-07-08 at 7 01 19 PM](https://user-images.githubusercontent.com/48804258/86948435-6935d680-c14d-11ea-9e15-b1d639ea36ad.png)


### Top 3 articles section

- **Large version** 

- [x] The TNW logo should be present in the top left corner of the large image. This was pointed out to you in a previous review. Please add this. 
Your clone 👇 
![Screen Shot 2020-07-08 at 7 02 47 PM](https://user-images.githubusercontent.com/48804258/86948583-9edabf80-c14d-11ea-9e74-b2a2cacf7855.png)
The original page 👇 

![Screen Shot 2020-07-08 at 7 03 11 PM](https://user-images.githubusercontent.com/48804258/86948618-abf7ae80-c14d-11ea-80a1-10d8535992de.png)



- **Medium & Small version**

- [x] The two smaller images on the side do not appear to be responsive. They are being cut off when the screen shrinks. Please fix this in both the small and the medium screen. 
Your clone (medium) 👇 
![Screen Shot 2020-07-08 at 7 05 50 PM](https://user-images.githubusercontent.com/48804258/86948839-0abd2800-c14e-11ea-86c3-a6eb5512906b.png)
Your clone (small) 👇 
![Screen Shot 2020-07-08 at 7 06 18 PM](https://user-images.githubusercontent.com/48804258/86948876-1ad50780-c14e-11ea-80b5-296cf91d5ec7.png)
_hint: You can try using `background-size: cover` to fix this_


### Latest news section

- **Large version** 

- [x] This section does not look like the original as was pointed out to you in a previous review. It appears to be left-aligned as there is more space on the right. It should be centered. Please compare your clone with the original page and fix this. 
Your clone 👇 
![Screen Shot 2020-07-08 at 7 11 39 PM](https://user-images.githubusercontent.com/48804258/86949389-dbf38180-c14e-11ea-9da7-30b8971db74b.png)
The original page 👇 
![Screen Shot 2020-07-08 at 7 12 38 PM](https://user-images.githubusercontent.com/48804258/86949484-fe859a80-c14e-11ea-9c89-132c2ee91d3c.png)
- **Small version**

- [x] It also does not look like the original on the small screen size. The article title as well as the small font should be right next to the image. Please compare your clone with the original and fix this. 
Your clone 👇 
![Screen Shot 2020-07-08 at 7 15 21 PM](https://user-images.githubusercontent.com/48804258/86949728-5f14d780-c14f-11ea-8518-ba66d0e9a954.png)
The original page 👇 
![Screen Shot 2020-07-08 at 7 15 40 PM](https://user-images.githubusercontent.com/48804258/86949760-6a680300-c14f-11ea-87f1-27047a131bbc.png)

### Categories (Apps, Gear, Tech, etc) section

- **Large version** 

- [x] You are missing a row of categories in this section. There should be three rows of three categories whereas in yours there is only one row. 

- **Medium version**

- [x] The categories should align to two categories per row in the medium screen. 
Your clone 👇 
![Screen Shot 2020-07-08 at 7 19 49 PM](https://user-images.githubusercontent.com/48804258/86950103-fed26580-c14f-11ea-8622-a0acc707725d.png)
The original page 👇 
![Screen Shot 2020-07-08 at 7 20 18 PM](https://user-images.githubusercontent.com/48804258/86950151-101b7200-c150-11ea-9393-b33060fa59e6.png)

### Latest deals section

- **Small version**

- [x] The same issue from the latest news section is also present in this section. Please compare your clone with the original page and fix this. 
Your clone 👇 
![Screen Shot 2020-07-08 at 7 21 49 PM](https://user-images.githubusercontent.com/48804258/86950294-45c05b00-c150-11ea-8178-b4ea65e2c55c.png)
The original page 👇 
![Screen Shot 2020-07-08 at 7 22 07 PM](https://user-images.githubusercontent.com/48804258/86950320-51ac1d00-c150-11ea-8041-22ce800a188c.png)


### Footer

- [x] Your footer still does not look like the original. This was pointed out to you in a previous review. Please compare your clone with the original page paying close attention to the colors. 
The original page 👇 
![Screen Shot 2020-07-08 at 7 23 34 PM](https://user-images.githubusercontent.com/48804258/86950503-84eeac00-c150-11ea-91f9-9e10f10c68b2.png)
Your clone 👇 
![Screen Shot 2020-07-08 at 7 23 49 PM](https://user-images.githubusercontent.com/48804258/86950555-8e781400-c150-11ea-963c-90404a353d8e.png)

- [x] Additionally, there is unnecessary white space below your footer. Please ensure that your footer extends all the way to the bottom of the page. 
![Screen Shot 2020-07-08 at 7 24 53 PM](https://user-images.githubusercontent.com/48804258/86950647-b49db400-c150-11ea-895f-682f498c434e.png)


### [OPTIONAL]

- Your clone appears to have two "Latest News" sections. Feel free to remove one of these as it is not needed. The additional section is right above the "Latest Deals" Section. 

- This project should not have any media queries for the mobile view as it is a media first project. I am sorry that this was not pointed out to you in previous reviews therefore I will not mark it as a required change. However, you are free to implement this if you would like.
Screenshot of requirements from pathwright 👇 
![Screen Shot 2020-07-08 at 7 29 03 PM](https://user-images.githubusercontent.com/48804258/86951045-49a0ad00-c151-11ea-835a-0c4f37ffca38.png)

- The HTML validator is showing a warning. However, as it is not an error you are not required to fix this.
![Screen Shot 2020-07-08 at 7 29 56 PM](https://user-images.githubusercontent.com/48804258/86951148-6937d580-c151-11ea-84d4-7c00cc378501.png)






****

### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-07-08 21:11 UTC, expjazz requested changes
## Hey @lucianosarno  and @karthykarthick 
### [status: Change Required]

#### You did a good work on this project, but we still need to changes a few things as pointed out by the TSE's above:

### Top 3 articles section
#### Now you have the TNW logo on the large screen, which is great, but this logo needs to be removed in the medium screen sizes. This was not informed by the TSE's above because it was not there.
Yours
:point_down:
![image](https://user-images.githubusercontent.com/61479648/86967627-44d3fd00-c141-11ea-882f-bd705ec72a1d.png)

Original
:point_down:
![image](https://user-images.githubusercontent.com/61479648/86967736-6a610680-c141-11ea-9c21-9502ebf799d0.png)


### Footer
#### There are still a few things to adjust in the footer. Please do these changes as required by the last TSE's:

- [ ]  Your footer still does not look like the original. This was pointed out to you in a previous review. Please compare your clone with the original page paying close attention to the colors and to the unnecessary whitespace below your footer.

The original page
:point_down:
![image](https://user-images.githubusercontent.com/61479648/86966332-5f0cdb80-c13f-11ea-8c88-d05abe397b22.png)

Yours
:point_down:
![image](https://user-images.githubusercontent.com/61479648/86970712-36d4ab00-c146-11ea-861d-a7e8046e0fdb.png)


[OPTIONAL]

- I think you could add more padding on the right and the left (on the whole page), just like the original one. 

### Please make the required changes and resubmit for a new code review once you are ready

Good Luck and Happy Coding :pray:

P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).

2020-07-08 22:22 UTC, expjazz requested changes
## [Changes Required]

#### Good work on working on the changes requested, but we still need one more detail:

##### We still have the problem on the footer. If you remove the margin of the last h3 with the class of 'footer__copyright' you will solve these issues. 

### As stated above, the project looks really great! :pray:

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding 

P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:

2020-07-08 23:10 UTC, bertil291utn commented
# Status: on review 🟠 

##### Do you have any question? *Reach out to me on* [Twitter](bit.ly/bertil-twitter) , [LinkedIn](bit.ly/bertil_linkedin) or Slack Microverse-community as @btandayamo

2020-07-09 00:00 UTC, bertil291utn commented
**Status:** Changes requested 🔴  

# Hey guys, you've done a great job

Congratulations guys you've worked so hard on this project I'd like to approve however you still need to make some changes.

First of all 

* [ ] Your GitHub flow it looks so professional you mastered it however be careful with your pull request and commits messages must be more meaningful, and also your README file doesn't look like a professional one, next time your project will be rejected. 
  ![image](https://user-images.githubusercontent.com/24902525/86980531-aac48280-c149-11ea-9cbd-977ec6df4785.png)

![image-20200708183603181](C:\Users\Bertil\AppData\Roaming\Typora\typora-user-images\image-20200708183603181.png)

- [ ] Accomplish according to the actual web page. I'm going to give the exact breakpoints where you have to work and then compare it with yours if it's the same as the original one move to the next breakpoint.

- **425px**
  ![image](https://user-images.githubusercontent.com/24902525/86981051-2672ff00-c14b-11ea-988f-9dc339206226.png)



- **768px**

![image](https://user-images.githubusercontent.com/24902525/86981108-57533400-c14b-11ea-9f99-91bc9fac5b8d.png)

- **1024px**

![image](https://user-images.githubusercontent.com/24902525/86981136-66d27d00-c14b-11ea-855c-ff41fddf93b7.png)



- [ ] Certainly, the main goal with this project is to work with responsiveness but you have to work also doing a [clone](https://www.theodinproject.com/courses/html5-and-css3/lessons/building-with-responsive-design). So work on typos, colors, and spaces (paddings and margins), I'm not worried about the content.

  ![image](https://user-images.githubusercontent.com/24902525/86981344-e95b3c80-c14b-11ea-894d-b69e7053cc60.png)

Guys please work on these requested changes and request another review, I'm sure the next one you got approved, you don't have reason to rush upon your assignments



> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

Good luck. 
:shipit: ? Not yet

<hr>

##### Do you have any question? *Reach out to me on* [Twitter](bit.ly/bertil-twitter), [LinkedIn](bit.ly/bertil_linkedin) or Slack Microverse-community like @btandayamo

2020-07-09 08:54 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: :stop_sign: 
### HELLO @lucianosarno :wave: AM PETER ROBERT A TSE AND I HAVE REVIEWED YOUR PROJECT.

- [x] There still changes required on this project the reason being you haven't yet worked on major issues as pointed out by the previous TSE. 
Most of the sections on your web page as pointed out by @BrittanyBlake don't resemble the original. Kindly you need to go back and check on the suggestions that were given work on them before submitting your project for another review. Your project can not be approved unless this is done.

The same reasons that @peterrobert  and @BrittanyBlake pointed out earlier are the same ones that have prevented me from approving this project. Kindly take a step back and work on them

**If you have any questions feel free to reach out to me via slack** @peterrobert

2020-07-09 14:42 UTC, lucianosarno commented
> ### CHANGES REQUIRED ♻️ 🛑
> ### HELLO @lucianosarno 👋 AM PETER ROBERT A TSE AND I HAVE REVIEWED YOUR PROJECT.
> * [ ]  There still changes required on this project the reason being you haven't yet worked on major issues as pointed out by the previous TSE.
>   Most of the sections on your web page as pointed out by @BrittanyBlake don't resemble the original. Kindly you need to go back and check on the suggestions that were given work on them before submitting your project for another review. Your project can not be approved unless this is done.
> 
> The same reasons that @peterrobert and @BrittanyBlake pointed out earlier are the same ones that have prevented me from approving this project. Kindly take a step back and work on them
> 
> **If you have any questions feel free to reach out to me via slack** @peterrobert

Ok Peter, thanks for bringing your considerations and We're sorry for the confusion on this project.
We're going to work on @peterrobert  and @BrittanyBlake suggestions and ask for a new review!

2020-07-09 16:20 UTC, bertil291utn commented
# Project Approved ✔️ :shipit:

Hi, guys, your project was approved, please merge to master branch and move on with the next assignment.

You're doing  a great job keep going 💻 🚀 🔥

[WARNING INFO]

- These assignments also are to work on clone skills, next time be careful on fonts, color, and each detail

<hr>

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

##### Do you have any question? *Reach out to me on* [Twitter](bit.ly/bertil-twitter), [LinkedIn](bit.ly/bertil_linkedin) or Slack Microverse-community like @btandayamo

2020-07-09 16:24 UTC, merged